# 
# Copyright 2018-2020 By-Ameng
# Licensed to the public under the GPL V3 License.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=luci-app-samba-mar
LUCI_DEPENDS:=+samba36-server
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=202000201

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
